redis_uri: "redis://127.0.0.1:6379"
application:
  port: 8002
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "dmytro.d@spyingcrow.com"
  authorization_token: "email-service-provider-token"
  timeout_milliseconds: 10000